name: make
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: yegor256/latexmk-action@0.1.20
        with:
          opts: -pdf
          packages: xkeyval libertine minted fvextra catchfile xstring framed tcolorbox environ anyfontsize chngcntr lastpage paralist enumitem qrcode
